// Package translation defines the provider-agnostic translation layer.
//
// The application depends on Service, never on a concrete provider.
// MockService validates the pipeline now; a Gemini-backed implementation
// will be added later behind the same interface.
package translation

import (
	"context"
	"errors"
	"fmt"
	"time"
)

// Language identifies a supported spoken language.
type Language string

const (
	LanguagePortuguese Language = "PT-BR"
	LanguageEnglish    Language = "EN-US"
	LanguageSpanish    Language = "ES-ES"
	LanguageFrench     Language = "FR-FR"
)

// SupportedLanguages lists the languages accepted by the translation layer.
var SupportedLanguages = []Language{
	LanguagePortuguese,
	LanguageEnglish,
	LanguageSpanish,
	LanguageFrench,
}

// Valid reports whether the language is supported.
func (l Language) Valid() bool {
	switch l {
	case LanguagePortuguese, LanguageEnglish, LanguageSpanish, LanguageFrench:
		return true
	default:
		return false
	}
}

const (
	// AudioCodecPCM16LE matches the signed 16-bit little-endian PCM used by
	// the call protocol.
	AudioCodecPCM16LE = "PCM-INT16-LE"
)

// DefaultAudioFormat is the format of the frames produced by the call protocol.
var DefaultAudioFormat = AudioFormat{
	Codec:          AudioCodecPCM16LE,
	SampleRate:     16000,
	Channels:       1,
	BytesPerSample: 2,
}

// AudioFormat describes the encoding of an audio buffer.
type AudioFormat struct {
	Codec          string `json:"codec"`
	SampleRate     int    `json:"sample_rate"`
	Channels       int    `json:"channels"`
	BytesPerSample int    `json:"bytes_per_sample"`
}

// AudioInput is a raw audio buffer together with its encoding and optional
// stream metadata.
type AudioInput struct {
	Format    AudioFormat `json:"format"`
	Data      []byte      `json:"data"`
	StreamID  uint32      `json:"stream_id,omitempty"`
	Sequence  uint32      `json:"sequence,omitempty"`
	Timestamp uint32      `json:"timestamp,omitempty"`
}

// Transcription is the recognized speech produced from an audio input.
type Transcription struct {
	Text       string   `json:"text"`
	Language   Language `json:"language"`
	Confidence float64  `json:"confidence"`
}

// AudioOutput is an audio buffer generated by the provider, such as translated
// speech.
type AudioOutput struct {
	Format AudioFormat `json:"format"`
	Data   []byte      `json:"data"`
}

// Request describes a single translation operation.
type Request struct {
	ID             string     `json:"id"`
	Audio          AudioInput `json:"audio"`
	SourceLanguage Language   `json:"source_language"`
	TargetLanguage Language   `json:"target_language"`
}

// Result is the complete outcome of a translation request.
type Result struct {
	ID              string        `json:"id"`
	SourceLanguage  Language      `json:"source_language"`
	TargetLanguage  Language      `json:"target_language"`
	Transcription   Transcription `json:"transcription"`
	TranslatedText  string        `json:"translated_text"`
	TranslatedAudio AudioOutput   `json:"translated_audio"`
	CreatedAt       time.Time     `json:"created_at"`
}

// Service translates audio from a source language to a target language.
type Service interface {
	// Name identifies the provider implementation for logging and diagnostics.
	Name() string
	// Translate consumes audio in the source language and returns the original
	// transcription plus translated text and audio.
	Translate(ctx context.Context, request Request) (*Result, error)
}

var (
	ErrInvalidRequest       = errors.New("invalid translation request")
	ErrUnsupportedLanguage  = errors.New("unsupported language")
	ErrEmptyAudio           = errors.New("audio input is empty")
	ErrInvalidAudioFormat   = errors.New("audio format is not supported")
	ErrProviderNotAvailable = errors.New("translation provider is not available")
	ErrUnknownProvider      = errors.New("unknown translation provider")
)

// ValidateRequest returns the canonical validation error for a request, or nil.
func ValidateRequest(request Request) error {
	switch {
	case request.ID == "" || len(request.ID) > 64:
		return fmt.Errorf("%w: id must contain 1 to 64 bytes", ErrInvalidRequest)
	case request.SourceLanguage == "" || request.TargetLanguage == "":
		return fmt.Errorf("%w: source_language and target_language are required", ErrInvalidRequest)
	case !request.SourceLanguage.Valid():
		return fmt.Errorf("%w: %q", ErrUnsupportedLanguage, request.SourceLanguage)
	case !request.TargetLanguage.Valid():
		return fmt.Errorf("%w: %q", ErrUnsupportedLanguage, request.TargetLanguage)
	case len(request.Audio.Data) == 0:
		return ErrEmptyAudio
	case !validAudioFormat(request.Audio.Format):
		return fmt.Errorf("%w: codec=%q rate=%d channels=%d", ErrInvalidAudioFormat,
			request.Audio.Format.Codec, request.Audio.Format.SampleRate, request.Audio.Format.Channels)
	default:
		return nil
	}
}

func validAudioFormat(format AudioFormat) bool {
	return format.Codec == AudioCodecPCM16LE &&
		format.SampleRate > 0 &&
		format.Channels > 0 &&
		format.BytesPerSample > 0
}